name: spagreen
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  jitsi_meet: ^1.2.0
  flutter_bloc: ^3.2.0
  convex_bottom_bar: ^2.4.1
  dio: ^3.0.10
  hive: ^1.4.3
  hive_flutter: ^0.3.1
  built_value: ^7.1.0
  equatable: ^1.2.3
  provider: ^4.3.2
  firebase_auth: ^0.18.3+1
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.1
  country_code_picker: ^1.4.0
  pin_entry_text_field: ^0.1.4
  fluttertoast: ^7.1.5
  flutter_keyboard_visibility: ^3.2.1
  intro_slider: ^2.3.1
  after_layout: ^1.0.7+2
  flutter_html: ^1.0.2
  share: ^0.6.4+3
  onesignal_flutter: ^2.6.0
  app_review: ^2.0.1
  image_picker: ^0.6.7+4
  flutter_spinkit: ^4.1.2+1
  flutter_pagewise: ^1.2.3
  admob_flutter: ^1.0.1
  connectivity: ^0.4.9
  sign_in_with_apple: ^2.5.2
  firebase_core: ^0.5.2+1


dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner:
flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/android_launcher_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/authImage/
    - assets/images/common/
    - assets/images/introImage/
    - assets/images/tabs/


  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/nunito_sans/NunitoSans-Black.ttf
        - asset: assets/fonts/nunito_sans/NunitoSans-BlackItalic.ttf
        - asset: assets/fonts/nunito_sans/NunitoSans-Bold.ttf
        - asset: assets/fonts/nunito_sans/NunitoSans-BoldItalic.ttf
        - asset: assets/fonts/nunito_sans/NunitoSans-ExtraBold.ttf
        - asset: assets/fonts/nunito_sans/NunitoSans-Light.ttf
        - asset: assets/fonts/nunito_sans/NunitoSans-Regular.ttf
        - asset: assets/fonts/nunito_sans/NunitoSans-SemiBold.ttf
        - asset: assets/fonts/nunito_sans/NunitoSans-SemiBoldItalic.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages